tasks:
  build:
    cmd: go
    args:
      - build
      - ./...

  test:
    cmd: go
    args:
      - test
      - ./...
    depends_on:
      - build

  deploy:
    cmd: echo
    args:
      - deploying...
    depends_on:
      - test

  all:
    cmd: echo
    args:
      - workflow
    depends_on:
      - deploy